### ISSUE TITLE
Eclipse Problem

### ISSUE THREAD

**Issue by f4n** [backuity/p2s#2]
Hi,
i cloned your project and build it with maven sucessfully. But if i want to execute the Hocon Test in Eclipse (Luna) i get the following error: 

Caused by: java.lang.ClassNotFoundException: some.other.pkg.ConversionSettingsProperties
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.p2s.SettingsFactory.load(SettingsFactory.java:45)
	... 32 more

It always searches for a "$(ConfigClassName)Properties" class.
In target/generated-test-sources/test-annotations/some/other/pkg is a ConversionSettingsProperties.java file but wich process is creating this file?
Do you have any idea how to use it in Eclipse? 

Kind regards
f4n

**Comment by backuitist** [comment]
There was actually a bug when using the Eclipse compiler. This has been fixed in 2.3.
Thanks
