### ISSUE TITLE
Support Collection

### ISSUE THREAD

**Issue by cthiebault** [backuity/p2s#4]
```
@Settings
 public interface SomeSettings {
     Collection<String> strings();
 }
```

Produce

```
Caused by: java.lang.RuntimeException: Failed to process java.util.CollectionProperties
        at org.p2s.SettingsProcessor.processClass(SettingsProcessor.java:79)
        at org.p2s.SettingsProcessor.processClass(SettingsProcessor.java:76)
        ... 36 more
Caused by: java.lang.RuntimeException: Method contains(java.lang.Object) of CollectionProperties has parameters : arg0
        at org.p2s.SettingsProcessor.processClass(SettingsProcessor.java:65)
```

**Comment by backuitist** [comment]
Fixed in 2.4
